set -g prefix C-a #
unbind C-b # C-b即Ctrl+b键，unbind意味着解除绑定
bind C-a send-prefix # 绑定Ctrl+a为新的指令前缀


# 绑定快捷键为r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded.."


#开启鼠标支持
set-option -g mouse on

# 窗口指令
##打开一个新窗口
bind-key c new-window -c "#{pane_current_path}" 

## 分窗指令 
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"


## 绑定hjkl键为`面板切换`的上下左右键
bind -r k select-pane -U # 绑定k为↑
bind -r j select-pane -D # 绑定j为↓
bind -r h select-pane -L # 绑定h为←
bind -r l select-pane -R # 绑定l为→

bind -r e lastp # 选择最后一个面板
bind -r ^e last # 选择最后一个窗口

bind -r ^u swapp -U # 与前一个面板交换位置
bind -r ^d swapp -D # 与后一个面板交换位置

## 绑定Ctrl+hjkl键为<font color=red>面板上下左右调整边缘</font>的快捷指令,需要前缀ctrl+a  
bind -r C-k resizep -U 5 # 绑定Ctrl+k为往↑调整面板边缘10个单元格
bind -r C-j resizep -D 5 # 绑定Ctrl+j为往↓调整面板边缘10个单元格
bind -r C-h resizep -L 5 # 绑定Ctrl+h为往←调整面板边缘10个单元格
bind -r C-l resizep -R 5 # 绑定Ctrl+l为往→调整面板边缘10个单元格

#显示颜色

set-option -sa terminal-overrides ',screen-256color:RGB'

# 设置窗口起始序号为1
set -g base-index 1

# 获取创造的快照
source-file ~/.config/nvim/airline.tmux
if-shell "test -f ~/.config/nvim/airline.tmux" "source ~/.config/nvim/airline.tmux"




#==========tmux插件管理器==============
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# 用于重启系统后恢复tmux的布局 
set -g @plugin 'tmux-plugins/tmux-resurrect'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

####################################33





